### ISSUE TITLE
Update credential-support version

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/ca-engine#20]
A new version of credential support is available which allows unlimited updates to the certificate chain.

When updating to this version The ExternalChainCredential added in 1.2.2 should be deleted again.
Implementations using 1.2.2 should use the latest version of credential-support and should NOT use ExternalChainCredential.

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/ca-engine/pull/21.
