### ISSUE TITLE
Upgrade commons-beanutils

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/ca-engine#22]
A transitive dependency on commons-beanutils has vulnerabilities and should be upgraded from 1.9.3 to the fixed version 1.9.4.

The source of this dependency comes from org.jvnet.jaxb2_commons:jaxb2-basics-tools:0.12.0, which in turn comes from se.swedenconnect.schemas.cert:authcontextinfo10-jaxb:2.0.0

**Comment by martin-lindstrom** [comment]
Fixed
